CMAKE_MINIMUM_REQUIRED(VERSION 3.0 FATAL_ERROR)

INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(ZOOKEEPER_LIBRARY zookeeper_mt REQUIRED)
FIND_PATH(ZOOKEEPER_INCLUDE_DIR "zookeeper/zookeeper.h")

SET(ZOOKEEPER_LIBRARIES ${ZOOKEEPER_LIBRARY})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Zookeeper
  REQUIRED_ARGS ZOOKEEPER_INCLUDE_DIR ZOOKEEPER_LIBRARIES)
